### ISSUE TITLE
Detalhes no código exemplo

### ISSUE THREAD

**Issue by patrickctrf** [lucasmaziero/lmic-rpi-fox#2]
Olá! Você poderia dar alguns detalhes acerca de como insiro informação a ser enviada e onde vejo seu recebimento no código dado como exemplo? (https://github.com/fox-iot/lmic-rpi-fox/tree/master/examples/ttn-abp-send)

Se eu puder entender como enviar e receber informação naquele código, faço um socket pra comunicar com python (minha aplicação). Pretendo comprar 1 par de shields Lora para raspberry, aqueles da Fox iot

Obrigado

**Comment by lucasmaziero** [comment]
Olá tudo tranquilo?

Na linha https://github.com/fox-iot/lmic-rpi-fox/blob/master/examples/ttn-abp-send/ttn-abp-send.cpp#L137 você tem a mensagem que será envida "Hello world!" com o incremento do contador.

Na linha https://github.com/fox-iot/lmic-rpi-fox/blob/master/examples/ttn-abp-send/ttn-abp-send.cpp#L110 é onde a mensagem é recebida, seu tamanho está em "LMIC.dataLen" e seu conteúdo "LMIC.frame[LMIC.dataBeg + i]", sendo que "i" deve ser percorrido até atingir o tamanho de "LMIC.dataLen", assim toda a mensagem é recuperada.

Ao Executar o exemplo você vai ver os logs no prompt de comando.

Fico a disposição.
